#!/system/bin/sh

# Device Information
export DEVICE_MANUFACTURER=`getprop ro.product.manufacturer`
export DEVICE_MODEL=`getprop ro.product.model`
export DEVICE_NAME="$DEVICE_MANUFACTURER $DEVICE_MODEL"
export DEVICE_CODENAME=`echo $DEVICE_MODEL | tr "[:upper:]" "[:lower:]"`

# Rotate the device screen 90°CW
export SDL_SCREEN_ROTATION=1

# Skip the SDL encoder ID check
export SDL_SKIP_ENCODER_ID_CHECK=1

# Tell SDL to blacklist unwanted joysticks
export SDL_JOYSTICK_DEVICE_BLACKLIST=touch_joypad:retrogame_joypad

# Override the ALSA default period size
export ALSA_DEFAULT_PERIOD_SIZE=960

# Force ALSA into MMAP mode
export ALSA_FORCE_MMAP=1

# The location of the brightness control
export LCD_BRIGHTNESS_PATH=/sys/devices/platform/sprd_backlight/backlight/sprd_backlight/brightness

# The location of the maximum brightness control value or the value itself
export LCD_BRIGHTNESS_MAXIMUM=/sys/devices/platform/sprd_backlight/backlight/sprd_backlight/max_brightness

# The minimum brightness value
export LCD_BRIGHTNESS_MINIMUM=1

# The battery capacity path
export BATTERY_CAPACITY_PATH=/sys/class/power_supply/battery/capacity
