#!/system/bin/sh

# Mount the rootfs loopback file
mount -t f2fs -o loop /boot/boot/rootfs.f2fs /root

# Bind mount the exfat partition
mount -o bind /boot /root/media

# Iterate the required folders
for f in dev dev/pts proc sys tmp firmware vendor/firmware lib/firmware lib/modules
do
        # Create a mount point
        mkdir -p /root/$f

        # And bind mount the folder to it
        mount -o bind /$f /root/$f
done

# Setup the shell environment
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export HOME=/root
export SHELL=/bin/sh

# And hand off control to the rootfs
chroot /root /usr/bin/init
